"""added merge data in artifacts schema

Revision ID: 7b4d7857863f
Revises: c7dff3266281
Create Date: 2026-07-05 15:44:09.591514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b4d7857863f'
down_revision: Union[str, Sequence[str], None] = 'c7dff3266281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repository_artifacts', sa.Column('merged_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_unique_constraint('uix_repo_artifact_source', 'repository_artifacts', ['repository_id', 'artifact_type', 'source_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_repo_artifact_source', 'repository_artifacts', type_='unique')
    op.drop_column('repository_artifacts', 'merged_data')
    # ### end Alembic commands ###
