"""added processing stats in repository schema

Revision ID: e115a8336012
Revises: f5764e497146
Create Date: 2026-07-05 12:36:45.923082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e115a8336012'
down_revision: Union[str, Sequence[str], None] = 'f5764e497146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

processing_status = postgresql.ENUM(
    "pending",
    "processing",
    "ready",
    "failed",
    name="repository_processing_status",
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    processing_status.create(op.get_bind(), checkfirst=True)

    op.drop_constraint(op.f('uix_conversation_id_user_id'), 'messages', type_='unique')
    op.add_column('repositories', sa.Column('processing_status', processing_status, nullable=False, server_default="pending",))
    op.add_column('repositories', sa.Column('processing_progress', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_repository_artifacts_id'), 'repository_artifacts', ['id'], unique=False)
    op.create_index(op.f('ix_repository_artifacts_repository_id'), 'repository_artifacts', ['repository_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_artifacts_repository_id'), table_name='repository_artifacts')
    op.drop_index(op.f('ix_repository_artifacts_id'), table_name='repository_artifacts')
    op.drop_column('repositories', 'processing_progress')
    op.drop_column('repositories', 'processing_status')
    processing_status.drop(op.get_bind(), checkfirst=True)
    op.create_unique_constraint(op.f('uix_conversation_id_user_id'), 'messages', ['conversation_id', 'user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
