"""add repository artifacts schema

Revision ID: f5764e497146
Revises: 001_initial
Create Date: 2026-07-05 11:41:06.332904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5764e497146'
down_revision: Union[str, Sequence[str], None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repository_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repository_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'indexed', 'skipped', 'failed', name='artifact_status'), nullable=False),
    sa.Column('normalized_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enriched_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skip_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repository_artifacts_repository_id'), table_name='repository_artifacts')
    op.drop_index(op.f('ix_repository_artifacts_id'), table_name='repository_artifacts')
    op.drop_table('repository_artifacts')
    # ### end Alembic commands ###
